[project]
name = "github-cli-auth"
version = "0.1.0"
description = "GitHub CLI Authentication and Commit Tool with Descope"
readme = "README.md"
requires-python = ">=3.8.1"
dependencies = [
    "pygithub>=2.7.0",
    "descope>=1.7.8",
]

[project.scripts]
github-cli = "main:main"
