[project]
name = "adi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "descope>=1.7.8",
    "openai>=1.99.9",
    "pygithub>=2.7.0",
    "setuptools>=80.9.0",
]
